[functions]
  external_node_modules = ["express", "mongodb"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/v1/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/api/v1/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
